apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sample-go-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-go-basic
    app.kubernetes.io/part-of: devfile-sample-go-basic
  name: sample-go-basic
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: sample-go-basic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: sample-go-basic
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sabhardw-tenant/devfile-sample-go-basic/sample-go-basic@sha256:362a0220dce7af70bdf4e93e32c9576e71a5ecbc5527ef6d14306d51cbb72c21
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
