apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: sample-go-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sabhardw-tenant/devfile-sample-go-basic/sample-go-basic@sha256:0a7ecaed3e1a653d89db026e973aaa44d8777f73ae6292c7fdafaf6ee2fad932
        name: my-go
        resources: {}
status: {}
