apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: sample-go-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sabhardw-tenant/devfile-sample-go-basic/sample-go-basic@sha256:ec1452b2adec849f5fceca83233f8e8f1456aba6f53e76f717a2c725c4050fc6
        name: my-go
        resources: {}
status: {}
